name: Python Test Package

on:
  pull_request:
    branches:
    - main

jobs:
  test-github:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache-dependency-path: requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip --no-cache-dir
        python -m pip install -r requirements.txt
        python -m spacy download en_core_web_md
    - name: Test with pytest
      run: |
        pytest tests.py
  
  test-leafcloud:
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Build Container = Unit Tests
      run: docker build . --progress=plain
  
  github-docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Build Container = Unit Tests
      run: docker build . --progress=plain

